- src/components/KakaoMap/index.tsx
- src/components/KakaoMapMarker/GeneralMarker.tsx
- src/contexts/MapProvider/index.tsx
- src/contexts/Providers.tsx
- src/hooks/useAsync.ts
- src/pages/map/index.tsx
- 이전 PR에 실수로 push하지 못한 커밋이 있어서 재 PR합니당
> ♻️ refactor: map을 context를 이용하여 전역 상태 관리

- src/components/domain/TopNavigation/index.tsx
- src/contexts/NavigationProvider/actionTypes.ts
- src/contexts/NavigationProvider/context.ts
- src/contexts/NavigationProvider/index.tsx
- src/contexts/NavigationProvider/reducer.ts
- src/contexts/NavigationProvider/types.ts
- src/pages/login/index.tsx
전페이지에서 TopNavigation의 텍스트와 이벤트를 바인딩하실 수 있습니다.
상단 바에 취소 버튼을 각 페이지에 원하는 이벤트로 바인딩할 수 있습니다.
> ✨ feat: CustomButton 이벤트바인딩

- src/pages/_app.tsx
- src/styles/theme.ts
- src/types/emotion.d.ts
Co-authored-by: grighth12 <grighth12@users.noreply.github.com>
Co-authored-by: Parkserim <Parkserim@users.noreply.github.com>
theme provider 등록
closes #50
> ✨ feat: theme provider 등록

- src/components/base/Spacer/index.tsx
- src/components/domain/Favorites/index.tsx
- src/pages/courts/create.tsx
- src/pages/hanna/index.tsx
- src/pages/index.tsx
- src/pages/user/edit/index.tsx
- spacer 컴포넌트를 theme provider로 규격화하고, css 속성을 이용하여 간단하게 리팩토링 하였습니다.
closes #60
- 기존 Spacer 컴포넌트를 사용했던 부분은 제가 사이즈 맞춰서 제대로 동작하도록 수정해놓았습니다!
> ♻️ refactor: spacer 컴포넌트 리팩토링

- src/components/base/Text/index.tsx
> ✨ feat: base Text 컴포넌트 스타일링

- src/components/base/Icon/index.tsx
- src/styles/theme.ts
> 💄 style: base Icon 컴포넌트 스타일링

- src/components/Reservations/CompletedReservations/index.tsx
- src/components/Reservations/Loudspeaker/index.tsx
- src/components/Reservations/UpcomingReservations/index.tsx
- src/pages/reservations/index.tsx
closes
- 확성기 버튼 한번 눌렀을 때, 경기 시작 시간 지났을 때  disable 되도록 구현하였습니다.
> ♻️ refactor: reservations 확성기 컴포넌트 리팩토링

- src/components/Reservations/CompletedReservations/index.tsx
- src/components/Reservations/UpcomingReservations/index.tsx
- src/components/base/Button/index.tsx
- src/components/base/Icon/index.tsx
- src/components/base/IconButton/index.tsx
- src/components/base/IconToggle/index.tsx
- src/components/base/ModalSheet/index.tsx
- src/components/base/Text/index.tsx
- src/components/domain/CourtItem/Address.tsx
- src/components/domain/CourtItem/ChatLink.tsx
- src/components/domain/CourtItem/Datetime.tsx
- src/components/domain/CourtItem/FavoritesToggle.tsx
- src/components/domain/CourtItem/Header.tsx
- src/components/domain/CourtItem/KakaoMapLink.tsx
- src/components/domain/CourtItem/ShareButton.tsx
- src/components/domain/CourtItem/index.tsx
- src/components/domain/CourtItem/style.tsx
- src/components/domain/Favorites/index.tsx
- src/components/domain/KakaoMapMarker/BasketballMarker.tsx
- src/components/domain/index.ts
- src/contexts/AuthProvider/actionTypes.ts
- src/contexts/AuthProvider/context.ts
- src/contexts/AuthProvider/index.tsx
- src/contexts/AuthProvider/reducer.ts
- src/contexts/AuthProvider/types.ts
- src/pages/courts/index.tsx
- src/pages/index.tsx
- src/pages/reservations/index.tsx
- src/styles/theme.ts
- 버튼 컴포넌트들을 Domain 폴더 밑에 만들었습니다.
- <CourtItem.Header ... /> <CourtItem.FavoriteToggle /> 과 같은 형태로 사용할 수 있습니다.
closes
- 버튼에 별도의 이벤트 핸들러 없이 정의된 props만 잘 넘기면 잘 작동되도록 만들어 놓았습니다!
2.png)
> ♻️  refactor: 공유, 채팅, 즐겨찾기, 지도 버튼 domain 공통 컴포넌트로 분리

- src/components/domain/TimeTable/TimeBlockUnits/Hour.tsx
- src/components/domain/TimeTable/TimeBlockUnits/style.tsx
- src/components/domain/TimeTable/index.tsx
- src/components/layout/DefaultLayout/Container.tsx
- src/pages/courts/[courtId]/[date].tsx
- src/pages/courts/index.tsx
> ✨ feat: 선택한 시간대로 예약 페이지 스크롤 포지션 설정

- src/components/domain/Favorites/index.tsx
closes #81
- 예약 하러가기 버튼의`<Link href="/">` 부분에 해당 농구장 예약페이지로 가는 링크 수정해야합니다.
- 카카오맵 버튼이 추가되어서 figma와 다른 디자인으로 구현했는데 괜찮을까요?
> 💄 style : favorites 페이지 스타일링

- src/pages/reservations/index.tsx
> 💄 style: reservations 페이지 상단 탭 스타일링

- src/components/domain/Favorites/index.tsx
> ✨ feat: isLoading인 경우 Skeleton UI 구현

- src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
- src/components/domain/ReservationItem/index.tsx
- src/pages/reservations/index.tsx
- src/service/reservationApi.ts
> ✨feat: 지나간 예약, 예약 참여자 토글 버튼 api 연동

- src/components/base/Avatar/index.tsx
> ✨ feat: default image 설정

- src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
- src/pages/reservations/index.tsx
- src/service/courtApi.ts
- src/service/reservationApi.ts
> feat: 지나간 예약 조회 api 연동

- src/components/base/Tab/TabItem.tsx
- src/components/base/Tab/index.tsx
- src/components/domain/NewCourtItem/index.tsx
- src/pages/admin/newcourts.tsx
관리자 페이지 스타일 작업
closes #104
- 관리자 페이지 스타일 작업했습니다.
> 💄style: 관리자 페이지 스타일 작업

- src/pages/courts/index.tsx
- 지도에 있는 마커 클릭시 courtId가 쿼리 스트링으로 들어가게 됩니다.
- 쿼리 스트링 여부에 따라 지도의 center가 해당 농구장의 위치로 지정됩니다.
closes
- 사항1
> ✨feat: 쿼리스트링 여부에 따른 지도 center restore

- src/components/domain/KakaoMapMarker/BasketballMarker.tsx
- @grighth12 님이 만드신 지도 마커에 각 상황에 따라 바뀌는 이미지가 바뀌는 마커를 제작해봤어요
#154
- 서버가 꺼져있는 상태라 화면 스크린샷은 넣지 못했습니다 따라서 테스트가 안되어있어요 분기점들을 나눠 놨습니다 혹시 틀렸다면 수정 부탁드려요~!
- 아래와 같은 이미지가 코트의 상태에 따라 변경 됩니다
> ✨ feat: 농구장 즐겨찾기 / 예약 태그 PNG, GIF 지도에 추가 #154

- src/components/domain/ReservationItem/ReservationItemBottom/index.tsx
- src/hooks/useInfiniteScroll.ts
- src/pages/reservations/index.tsx
- src/service/reservationApi.ts
- 무한 스크롤 훅 에러 해결했습니다.
closes
- 사항1
> ✨ feat: 지나간 예약 무한 스크롤 구현

- src/components/domain/LeadToLoginModal/index.tsx
- src/pages/courts/create.tsx
사용자가 새 농구장 정보 제출 시 confirm 모달 띄우도록 구현
> ✨ feat: 사용자가 새 농구장 정보 제출 시 confirm 모달 띄우도록 구현

- src/components/base/Tab/index.tsx
- src/components/domain/NewCourtItem/index.tsx
- src/components/domain/NewCourtItem/types.ts
- src/components/domain/ReservationItem/Loudspeaker/index.tsx
- src/pages/admin/newcourts.tsx
- src/pages/courts/create.tsx
- src/pages/reservations/index.tsx
- src/service/managementApi.ts
관리자 페이지 api 연동 및 무한 스크롤
closes #141 
- 무한 스크롤을 한나가 구현해줬습니다 😭
- 현재 처리 완료 탭에서 스크롤을 올릴 때 버벅이면서 올라가지 않는 현상이 있습니다.
> ✨ feat: 관리자 페이지 api 연동 및 무한 스크롤

- src/components/domain/Favorites/index.tsx
> 🔥 remove: 주소 출력 영역 제거

- src/components/domain/ReservationItem/Loudspeaker/index.tsx
- src/components/domain/ReservationItem/index.tsx
- src/contexts/SocketProvider/context.ts
- src/contexts/SocketProvider/index.tsx
> ✨ feat: 확성기 기능 연결

- src/components/base/Button/index.tsx
- src/components/domain/ReservationModalContent/HasBallDecisionModal.tsx
- src/pages/courts/index.tsx
- src/utils/timeTable.ts
> 한 자리 일월에 대한 예외처리 하여 배포

- .eslintrc.json
- src/components/base/Image/index.tsx
- src/components/base/Modal/index.tsx
- src/components/base/Slider/index.tsx
- src/components/base/Upload/index.tsx
- src/components/domain/KakaoLogin/index.tsx
- src/components/domain/KakaoMap/useKakaoMapEvent.ts
- src/components/domain/LinkAvatar/index.tsx
- src/components/domain/TopNavigation/index.tsx
- src/components/layout/DefaultLayout/index.tsx
- src/pages/admin/newcourts.tsx
- src/pages/login/redirect/index.tsx
scroll이벤트에 바인딩된 불필요한 이벤트가 발생되지 않도록 intersectionObserver로 성능 최적화했어요
TopnavigationSensor라는 styled컴포넌트를 더 만들어서 이 엘리멘트가 뷰포트와 인터섹션 되었을 때 이벤트가 발생되도록 리팩토링 했어요
혹시 더 좋은 대안이 있다면 알려주시면 감사할게요
> 상단 네비게이션 scroll 이벤트에서 인터섹션옵저버로 성능 최적화

- babel.config.js
- package.json
- src/utils/timeTable.test.ts
- src/utils/timeTable.ts
- tsconfig.json
- yarn.lock
- jest를 사용하여 timetable에 사용되는 유틸 함수들에 테스트 코드를 작성했습니다.
closes #202
- PR 이 머지된 경우 pull 받으신 후에 yarn을 한 번 돌려주세요!
- yarn test로 테스트 할 수 있습니다.
- 아직 test 코드를 어떻게 넣어야 할지 몰라서, 일단은 utils의 아래에 바로 넣었습니다. 좋은 구조라고는 생각되지 않아서 좀더 알아보고 수정하도록 하겠습니다.
> ✅ test: time table util함수 테스트 코드 작성
